spring:
  application:
    name: video-notes-to-wiki
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/video_notes
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  ai:
    ollama:
      base-url: ${app.llm.url}
      init:
        chat:
          additional-model: ${app.llm.chat.models.preferred}
        embedding:
          additional-model: ${app.llm.embeddings.models.preferred}
        pull-model-strategy: when_missing # NOTE we issue ar eques tot hte remote olllma service to have it pull. We are not running tha locally in the jvm or even the same.. service instance necessarily
        pull-model-strategy.max-retries: 2
    vectorstore:
      chroma:
        client:
          host: ${CHROMA_HOST:localhost}
          port: ${CHROMA_PORT:8000}
        initialize-schema: true

app:
  llm:
    chat:
      models:
        preferred: Qwen/Qwen3.5-9B
    embeddings:
      models:
        preferred: jinaai/jina-embeddings-v4
    url: ${OLLAMA_URL:http://localhost:8080/v1}
    contextWindowTokens: 4096 # TODO need to be absed on cofngured lllm for chat.
    maxChunkTokens: 4096
    reductionRatio: 0.3
    threadPoolSize: 5
    maxMemoryUsageMb: 1024
    promptOverheadTokens: 500
  vectordb:
    url: ${CHROMA_URL:http://localhost:8000}
  output:
    directory: ${OUTPUT_DIRECTORY:./output}
  video:
    drop:
      directory: ${VIDEO_DROP_DIRECTORY:./video-drop}
    transcribed:
      directory: ${TRANSCRIBED_DIRECTORY:./transcribed}
